name: CI

on: [push, pull_request]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install .
      - name: Install test runner
        run: |
          pip install pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
      - name: Build distributions
        run: |
          pip install hatch
          # Build all distributions (wheel + sdist) with Hatch
          hatch build